### ISSUE TITLE
Unable to open an Erudite book after installing EruditeExtensions

### ISSUE THREAD

**Issue by andswitch** [Cuis-Smalltalk/Erudite#16]
The system throws an error when selecting one of the "Read" or "Edit" entries in the Erudite menu.

It complains about 'bad number of arguments' when doing a call to `self perform: #markup` on an `EruditeMarkupGrammar` object.

I think the root of the problem is calling `perform:` with selectors whose methods are `AdvisedMethod` instances.

To confirm this, I changed a test case in the `MethodAdvisersTests` class to send `perform: #selector` instead of sending `selector` directly to the subject after installing the `AdvisedMethod`. This results in the same error.

**Comment by mmontone** [comment]
I see the error. I'm having a look.

**Comment by mmontone** [comment]
Yes, looks like a problem with MethodAdvisers.

**Comment by mmontone** [comment]
I wonder about two things: how was this working before? Or was it?

And: I'm not sure how fixable this is. `#perform:` is implemented as a vm primitive, and I'm replacing the CompiledMethod entry by an AdvisedMethod entry, and looks like the replacement doesn't go unnoticed by the vm.

**Comment by mmontone** [comment]
More precisely, error is: It is not possible to `#peform:` adivised methods. An 'Error: bad number of arguments' is signaled.

**Comment by mmontone** [comment]
Tried making AdvisedMethod subclass of ProtoObject instead of Object. But same error. And other errors appear.

**Comment by mmontone** [comment]
I've tested this in older images, and there are no problems there.

#peform: implementation looks like this in the image I've tested:

perform: arg1
	<primitive: 83>
	^ self
		perform: arg1
		withArguments: (Array new: 0).

**Comment by mmontone** [comment]
Reverting the #perform: method to its previous implementation above solves this issue with AdvisedMethods.

**Comment by mmontone** [comment]
This is fixed in https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/commit/c76613b84b8499970185858f9b22d68ceca8ca7c

**Comment by andswitch** [comment]
Amazing! Thank you so much for a very quick fix! 🚀
