### ISSUE TITLE
Remove gnuplot support from EruditeExtensions / EruditeMath

### ISSUE THREAD

**Issue by andswitch** [Cuis-Smalltalk/Erudite#18]
It turns out the `FunctionGraphMorph` in package `Morphic-Widgets-Extras` also lets one make plots.

You can display a plot in Erudite by simply inserting something like this in a document:

```smalltalk
[[[ | g d |
d := -1.
g := FunctionGraphMorph new.
g domain: (-4 to: 4).
g addFunction: [ :x | x \\ d ] color: Color green.
g addFunction: [ :x | x // d ] color: Color red.
g ]]] embedIt
```

Proposal: remove gnuplot support, instead use this morph for plots.

**Comment by mmontone** [comment]
Ok. I think I would preserve the gnuplot, as you may be able to do things you cannot with FunctionGraphMorph.

For FunctionGraphMorph, we could try to provide some specialized syntax (not sure exactly how); or easier, just mention how to embed graph morphs like you've done above, in the Erudite manual with some examples.

**Comment by mmontone** [comment]
I think it would fun to come up with some good FunctionGraphMorph examples that we can include in Erudite manual in a new "Plots" section.
