### ISSUE TITLE
Installing [Erudite] requires base system updates to #6247 but this system is updated to #6161.

### ISSUE THREAD

**Issue by cstes** [Cuis-Smalltalk/Erudite#19]
Hi,

I am raising this issue in Cuis-Smalltalk-Dev, Erudite and hilaire/drgeo.

There exists a git tag for Cuis)Smalltalk-Dev called BaseForCuis6.2.

If I clone the Cuis-S,alltalk-Dev repository and then git checkout BaseForCuis6.2, that works fine, and I get the repsoitory as tagged for Cuis 6.2 including the interesting V3 image for Cuis without "immediate Unicode characters" .

Howver I then subsequently "git clone" the Erudite repository  and try to install the Erudite package using

Feature require:'Erudite'

then the Cuis system raises an error and fails to install Erudite.

The message is : Installing [Erudite] requires base system updates to #6247 but this system is updated to #6161. Please install Cuis base system updates and retry. OK'

I tried running

ChangeSet installNewUpdates

that did not help, but in fact an alternative which I am more interested in, is trying to install Erudite "the way it was at the time of BaseForCuis6.2".

Is there a git tag please for the Erudite repo BaseForCuis6.2 so that Erudite can be git checkout'ed using a tag BaseForCuis6.2 so that I can install Erudite in a Cuis 6.2 system ?

The reason I also post this issue in hilaire/drgeo is because DrGeo instructs to intall Cuis6.2 and then to install Erudite (and SVG, Numerics, Parsers etc.)

Thanks,
David Stes

**Comment by cstes** [comment]
Would it please be possible to indicate which commit to checkout to get a version of the Erudite repository that is compatible with Cuis 6.2 ? If there is a git tag, that is more convenient, but I think that giving the numeric value of the git commit can also be used to git checkout that particular version of Erudite that can be installed in Cuis 6.2.

**Comment by mmontone** [comment]
This should work with Cuis 6.2: https://github.com/Cuis-Smalltalk/Erudite/commit/42fdfc310658bfa1715c19b4028fcafb4e6a23c1

**Comment by cstes** [comment]
I am sorry but that does not work.

I worry about the fact that it is required in Cuis to run the latest version and that it is not possible to run Erudite (or any other package) in an older version of Cuis.

What happens with git commit **42fdfc3** is that this seems to refer to Erudite version **1.240**.

When I run Cuis BaseFor 6.2 with an image called Cuis6.0-6143 I can start to install Erudite 1.240 and that works but then it wants PetitParser a version higher than 1.2.

I git clone the Parsers repository and obtain PetitParser 1.7.

When I try to use Erudite version 1.240 with PetitParser 1.7 it fails

I get a message:

UndefinedObject doesNotUnderstand: #isAlphaNumeric

This seems to be sent from the method _word_ in **PPPredicateObject**

I am not sure but I think maybe the nil object gets a #isAlphaNumeric message from the EruditeManual initialize or PPCurSetPredicate initializeOn: method.

What version of PetitParser should be used please to install Erudite on Cuis 6.2 (the Cuis6.0-6153 image from the Git tag BaseFor6.2.

It would also be nice to be able to install Erudite in a V3 image and fortunately the Cuis base for 6.2 release still supports the V3 image.

**Comment by mmontone** [comment]
I guess it might be: https://github.com/Cuis-Smalltalk/Parsers/commit/0e93d20997d924496a17ba280258aac4c7a469eb

But I cannot tell for sure. I don't have Cuis6.2 at hand at the moment.

It is bad that it is not possible to pin down dependencies for Cuis versions. At least I don't know how to do it.

**Comment by cstes** [comment]
If I git checkout 0e93d20 for the Parsers repository, I get PetitParser 1.6 and that works.   I mean that with that version of PetitParser, I can use the Cuis "Install Packages" to install Erudite version 1.240 (obtained by git checkout 42fdfc3) and PetitParser 1.6 which seem to be compatible and install on the "base" Cuis 6.2 image called Cuis-6.0-6153.image.   Thanks for your expert help, but as a less experienced Cuis user, I have to say that it is not obvious at all how to install Erudite on an older version of Cuis, so I am afraid the assumption is that I run the latest version of everything all the time ...  In that case, it makes no sense to release a Stable version because it turns out then that when you install the Stable version, you have more work and more problems than with the latest Unstable version.

**Comment by mmontone** [comment]
You are right. The stable version refers only to Cuis core, but should also
include versions of common packages too somehow. This issue could be raised
on the mailing list and someone could come up with a solution.

**Comment by cstes** [comment]
One possible improvement is to create symbolic Git tags like BaseForCuis6.2 also on the Parsers and Erudite repositories.   I can report that after some tests, I'm glad to see that it is still possible to install the Erudite package on Cuis 6.2.   I used to be subscribed to the Cuis mailing list in the past but I'm no longer on the list and it is also possible to comment on a github issue like this one.  Thanks for your help (and for the Erudite package).
