### ISSUE TITLE
Petit Parser - wrong version

### ISSUE THREAD

**Issue by thiagoslino** [Cuis-Smalltalk/Erudite#2]
Hi.
Error installing PetitParserTutorial. 
Petit Parser expected = 1.3
Petit Parser current  version (Cuis-Smalltalk /Parsers )= 1.2

Cuis version: #4253

**Comment by mmontone** [comment]
I think you have an old version: https://github.com/Cuis-Smalltalk/Erudite/blob/dc1aad99010dbb1e3badf48bf36935926eef0a94/Erudite.pck.st#L7

git pull and try again

**Comment by mmontone** [comment]
Ah. Sorry. In PetitParserTutorial!

**Comment by mmontone** [comment]
Ok. Changed it to 1.2.

https://github.com/Cuis-Smalltalk/Erudite/blob/df87f376175e9feb6d8ab43e3ab2e0c94321f92f/PetitParserTutorial.pck.st#L4

Thanks!

**Comment by mmontone** [comment]
Wrong line. This:

https://github.com/Cuis-Smalltalk/Erudite/blob/df87f376175e9feb6d8ab43e3ab2e0c94321f92f/PetitParserTutorial.pck.st#L6

**Comment by thiagoslino** [comment]
Tested, it works. Thank you.
