### ISSUE TITLE
Petit Parser tutorial error

### ISSUE THREAD

**Issue by thiagoslino** [Cuis-Smalltalk/Erudite#4]
Open the PetitParser tutorial and click on 'Parsing some input' raises the error 'Not enough elements'
![petitparser_book_error](https://user-images.githubusercontent.com/1688134/134012647-8e8594be-96b1-45f5-9821-f3e0154f04a0.png)

**Comment by mmontone** [comment]
@thiagoslino I've pushed a fix. Can you try again?

**Comment by thiagoslino** [comment]
Work like a charm!
Thank you

**Comment by mmontone** [comment]
:+1:
