### ISSUE TITLE
UML not parsed in nested book sections

### ISSUE THREAD

**Issue by andswitch** [Cuis-Smalltalk/Erudite#7]
It looks like UML is not being parsed in nested book sections.

At first glance it works, however after closing and reopening a UML book, only the UML in the top-level sections are images.

**Comment by mmontone** [comment]
Ohh. That's interesting ... I can't think of why that's happening .. I'll have a look soon.

**Comment by mmontone** [comment]
Maybe this is a deeper problem? Have you tried your math and plot stuff in non top-level sections?

**Comment by andswitch** [comment]
> Maybe this is a deeper problem? Have you tried your math and plot stuff in non top-level sections?

Indeed, I haven't tried that

/edit: just tried it. Exact same problem with formulas and plots.

/edit: so the explorer shows that the parsers in the documents of the subsections are not of the right class

**Comment by andswitch** [comment]
I fixed the problem in my image by moving the last statement of `EruditeBookSection>>subsections:` to `EruditeBookSection>>parent:` as the last statement.

This one: `subsections do: [ :ss | ss parent: self ]`.

I don't have time to create a PR right now. I can do it later.

**Comment by mmontone** [comment]
I've applied your fix. Thanks!
