### ISSUE TITLE
"save as" in editor does not preserve language extension

### ISSUE THREAD

**Issue by andswitch** [Cuis-Smalltalk/Erudite#8]
Clicking save-as in the editor seems to remove the language extension from the book. For example, the parser class method is not there in the new class of the book.

**Comment by mmontone** [comment]
The parser class meethod needs to be generated when creating a new book class from another. I'll have a look.

**Comment by mmontone** [comment]
I think I've fixed this.

**Comment by andswitch** [comment]
Thanks! This also seems to work for me.
